### ISSUE TITLE
download with dependencies link broken

### ISSUE THREAD

**Issue by lobpcg** [Reference-LAPACK/lapack#361]
Links to download with dependencies appear all broken, e.g.,
```
http://www.netlib.org/cgi-bin/netlibfiles.tgz?format=tgz&filename=/lapack/lapack_routine/dsyev.f
http://www.netlib.org/cgi-bin/netlibfiles.txt?format=txt&filename=/lapack/lapack_routine/dsyevd.f
```
all result in
```
Error: bad filename.
```

**Comment by julielangou** [comment]
Thank you, we will look into it very shortly.

**Comment by tchlux** [comment]
Unfortunately this is still broken. A solution to this issue is to replace

   http://www.netlib.org/cgi-bin/netlibfiles.tgz?format=tgz&filename=/lapack/lapack_routine/name
   http://www.netlib.org/cgi-bin/netlibfiles.txt?format=txt&filename=/lapack/lapack_routine/name
   http://www.netlib.org/cgi-bin/netlibfiles.zip?format=zip&filename=/lapack/lapack_routine/name

with

   http://www.netlib.org/cgi-bin/netlibfiles.pl?filename=/lapack/lapack_routine/name

Notice that instead of having the extension `tgz`, `txt`, or `zip`, you go to `.../netlibfiles.pl` and only provide the `filename` and not the `format`. That will give send you to a page where you can download the source files that you want.

(p.s. I put `name` in place of whatever LAPACK routine you would actually want, so the links here do not actually work)

**Comment by jprs22** [comment]
The workaround doesn't work for me, e.g. http://www.netlib.org/cgi-bin/netlibfiles.pl?filename=/lapack/lapack_routine/dgesvd.f gives "bad filename"

**Comment by tchlux** [comment]
My apologies! I forgot to fix the link after I realized it wasn't exactly correct. I'll update the instructions now, the text "/lapack_routine" needs to be stripped from the link and replaced with "/<type>" where in your example the type is "double". So the correct link is:

http://www.netlib.org/cgi-bin/netlibfiles.pl?filename=/lapack/double/dgesvd.f

**Comment by jprs22** [comment]
> My apologies! I forgot to fix the link after I realized it wasn't exactly correct. I'll update the instructions now, the text "/lapack_routine" needs to be stripped from the link and replaced with "/" where in your example the type is "double". So the correct link is:
> 
> http://www.netlib.org/cgi-bin/netlibfiles.pl?filename=/lapack/double/dgesvd.f

wow, that was quick. Thank you so much!

**Comment by benbarrowes** [comment]
This is still broken for me.

**Comment by tchlux** [comment]
> This is still broken for me.

What link are you trying to access?

**Comment by benbarrowes** [comment]
I am at:http://www.netlib.org/lapack/explore-html/d3/d01/group__complex16_g_ecomputational_ga56eeaaec72c76c53df90a3aed330f17a.html
If I click on the zip option, it sends me to here:http://www.netlib.org/cgi-bin/netlibfiles.zip?format=zip&filename=/lapack/lapack_routine/zhgeqz.f
Which says "error: bad filename"
bb




 

    On Thursday, June 11, 2020, 3:53:34 PM EDT, Thomas Lux <notifications@github.com> wrote:  
 
 



This is still broken for me.


What link are you trying to access?

**Comment by tchlux** [comment]
As per the instructions above, you should take the link they give:

http://www.netlib.org/cgi-bin/netlibfiles.zip?format=zip&filename=/lapack/lapack_routine/zhgeqz.f

Replace `.zip` with `.pl`, remove `format=zip&`, and substitute `lapack_routine/` for the type `complex16`. That gives the link

http://www.netlib.org/cgi-bin/netlibfiles.pl?filename=/lapack/complex16/zhgeqz.f

Which works just fine!

**Comment by benbarrowes** [comment]
Confirmed. It does work with dependencies. 

Any ETA for a general fix? Not just a workaround.

**Comment by benbarrowes** [comment]
And this download does not include BLAS dependencies it looks like (ZSCAL). Is that normal?

**Comment by tchlux** [comment]
> Any ETA for a general fix? Not just a workaround.

I don't know who maintains the website or how. It's been broken for more than a year now (I encountered this in 2018), so I suspect there will not be a fix anytime soon.

> And this download does not include BLAS dependencies it looks like (ZSCAL). Is that normal?

Yes that is normal. A lot of high performance (super) computers use custom `BLAS`, so those routines are not included in the `LAPACK` source downloads. I usually grab all the missing `BLAS` routines from source and concatenate them into a local file. The `BLAS` link is provided at the same place you get the `LAPACK` source.

**Comment by julielangou** [comment]
Should be working now... sorry for the delay.
We changed the server, and the script was no longer working.

**Comment by tchlux** [comment]
@julielangou it's still broken for LAPACK routine `dlassq`. The link to the `ZIP` given on explorer is this:
http://www.netlib.org/cgi-bin/netlibfiles.zip?format=zip&filename=/lapack/lapack_routine/dlassq.f90

But that fails with `Error: bad filename.` The suggested instructions above produce a working link:
http://www.netlib.org/cgi-bin/netlibfiles.pl?filename=/lapack/double/dlassq.f

**Comment by julielangou** [comment]
Sorry - forgot those f90 files - I just added them - your first link is working now
Julie
