### ISSUE TITLE
error: aggregate value used where an integer was expected

### ISSUE THREAD

**Issue by Frank-Dz** [Reference-LAPACK/lapack#375]
I use the latest version of LAPACK, yet there exists an error:
error: aggregate value used where an integer was expected

```
[ 71%] Building C object LAPACKE/CMakeFiles/lapacke.dir/src/lapacke_cgesvdq.c.obj
C:\local\lapack\LAPACKE\src\lapacke_cgesvdq.c: In function 'LAPACKE_cgesvdq':
C:\local\lapack\LAPACKE\src\lapacke_cgesvdq.c:69:34: warning: passing argument 21 of 'LAPACKE_cgesvdq_work' from incompatible pointer type [-Wincompatible-pointer-types]
                                  &rwork_query, lrwork );
                                  ^~~~~~~~~~~~
In file included from C:/local/lapack/LAPACKE/include/lapacke_utils.h:37,
                 from C:\local\lapack\LAPACKE\src\lapacke_cgesvdq.c:34:
C:/local/lapack/LAPACKE/include/lapacke.h:5778:40: note: expected 'float *' but argument is of type 'double *'
                                 float* rwork, lapack_int lrwork);
                                 ~~~~~~~^~~~~
C:\local\lapack\LAPACKE\src\lapacke_cgesvdq.c:74:5: error: aggregate value used where an integer was expected
     lcwork = (lapack_int)cwork_query;
     ^~~~~~
C:\local\lapack\LAPACKE\src\lapacke_cgesvdq.c:95:64: warning: passing argument 21 of 'LAPACKE_cgesvdq_work' from incompatible pointer type [-Wincompatible-pointer-types]
                                  iwork, liwork, cwork, lcwork, rwork, lrwork );
                                                                ^~~~~
In file included from C:/local/lapack/LAPACKE/include/lapacke_utils.h:37,
                 from C:\local\lapack\LAPACKE\src\lapacke_cgesvdq.c:34:
C:/local/lapack/LAPACKE/include/lapacke.h:5778:40: note: expected 'float *' but argument is of type 'double *'
                                 float* rwork, lapack_int lrwork);
```

**Comment by martin-frbg** [comment]
Probably same problem and solution as in https://github.com/Reference-LAPACK/lapack/pull/107

**Comment by martin-frbg** [comment]
Actually this was already fixed by #370 a few days after the 3.9.0 release.

**Comment by Frank-Dz** [comment]
> Actually this was already fixed by #370 a few days after the 3.9.0 release.

Thx! I successfully made the installation by using some method which get Lapack already compiled and it did well.

Thanks for your kind help and work!

Best,
Frank

**Comment by abhijeet-pandey** [comment]
Still getting the same error in lapack 3.9.0.
OS: Win 10
CMake: 3.17.3
gcc: 8.2.0-3

**Comment by martin-frbg** [comment]
@abhijeet-pandey this was fixed shortly **after** the 3.9.0 release and there has not been a newer release since. You will either need to apply the patch from #370 yourself, or build from the current develop branch.
